# Generated by Django 2.2.2 on 2019-06-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190618_1928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fcuser',
        ),
    ]
